package cnass;



import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;
import java.util.TimerTask;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Murtaza
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    
    static ServerSocket serverSocket;
    static Socket socket;    
    static DataInputStream dataInputStream;
    static DataOutputStream dataOutputStream;
    static int port;
    
    
    public Server() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Server_Area = new javax.swing.JTextArea();
        Send_Msg_Field_Server = new javax.swing.JTextField();
        Send_Button_Server = new javax.swing.JButton();
        Port_Field = new javax.swing.JTextField();
        Port_Label = new javax.swing.JLabel();
        Port_Set_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        Server_Area.setEditable(false);
        Server_Area.setColumns(20);
        Server_Area.setRows(5);
        jScrollPane1.setViewportView(Server_Area);

        Send_Msg_Field_Server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_Msg_Field_ServerActionPerformed(evt);
            }
        });

        Send_Button_Server.setText("Send");
        Send_Button_Server.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Send_Button_ServerActionPerformed(evt);
            }
        });

        Port_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Port_FieldActionPerformed(evt);
            }
        });

        Port_Label.setText("Port:");

        Port_Set_Button.setText("Listen");
        Port_Set_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Port_Set_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Send_Msg_Field_Server, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Send_Button_Server)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Port_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Port_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(Port_Set_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Port_Label)
                    .addComponent(Port_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Port_Set_Button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Send_Msg_Field_Server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Send_Button_Server)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Send_Msg_Field_ServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_Msg_Field_ServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Send_Msg_Field_ServerActionPerformed

    private void Send_Button_ServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Send_Button_ServerActionPerformed
        
        try 
        {
            
            String SendClientMsg ="";
            SendClientMsg = Send_Msg_Field_Server.getText().trim();      
            dataOutputStream.writeUTF(SendClientMsg);
            Send_Msg_Field_Server.setText("");
            
            
        } catch (IOException ex) {}
        
        
        
    }//GEN-LAST:event_Send_Button_ServerActionPerformed

    private void Port_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Port_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Port_FieldActionPerformed

    private void Port_Set_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Port_Set_ButtonActionPerformed
        
        if(Port_Field.getText()!=null)
        {
            port=Integer.parseInt(Port_Field.getText());

             try{
                serverSocket = new ServerSocket(port);
                socket = serverSocket.accept();
                Send_Button_Server.setEnabled(true);

                dataInputStream = new DataInputStream(socket.getInputStream());
                dataOutputStream =  new DataOutputStream(socket.getOutputStream());
             }catch(Exception E){}
        }
        
    }//GEN-LAST:event_Port_Set_ButtonActionPerformed
    public static void chatServer(){
        
       String RecieveClientMsg="";
       
            while(!RecieveClientMsg.equals("exit"))            
            {
               
           try {
               RecieveClientMsg = dataInputStream.readUTF();
               
                Server_Area.setText(Server_Area.getText().trim()+"\n"+RecieveClientMsg);
           } catch (IOException ex) {
               Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
           }
                
            }
    }
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) throws IOException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
                Send_Button_Server.setEnabled(false);
   
            }
        });
         Timer timer = new Timer();
        timer.schedule(new TimerTask() 
        {
            public void run() {
            chatServer();
            }
        }, 20*1000);
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Port_Field;
    private javax.swing.JLabel Port_Label;
    private javax.swing.JButton Port_Set_Button;
    private static javax.swing.JButton Send_Button_Server;
    private javax.swing.JTextField Send_Msg_Field_Server;
    private static javax.swing.JTextArea Server_Area;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
